version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566            # LocalStack Gateway
      - 4510-4559:4510-4559  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    volumes:
      - ${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh # Script de inicialização
      - ./deploy:/opt/deploy # Artifacts zipped for Lambda creation
    networks:
      - poc-net

networks:
  poc-net:
    driver: bridge
