{
 "title": "D - Feature Flags",
 "tags": [
  "feature-flags",
  "openfeature"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": "label_values(service_name)" }
  ]
 },
 "panels": [
  {
   "title": "Flag Evaluation Count (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (key) (rate(feature_flag_evaluation_requests_total{service_name=~\"$service\"}[1m]))",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Evaluation Results (Distribution)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (variant) (rate(feature_flag_evaluation_success_total{service_name=~\"$service\"}[5m]))",
     "legendFormat": "{{variant}}"
    }
   ]
  },
  {
   "title": "Evaluation Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(feature_flag_evaluation_error_total{service_name=~\"$service\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Feature Flag Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=~\"$service\"} |= \"FeatureFlag\""
    }
   ]
  }
 ]
}