version: '3.8'

services:
  # -----------------------------------------------------
  # GO Feature Flag (Feature Flags Backend)
  # Provides flag evaluation API and Swagger UI
  # Docs: https://gofeatureflag.org
  # -----------------------------------------------------
  gofeatureflag:
    image: gofeatureflag/go-feature-flag:v1.51.2
    container_name: gofeatureflag
    volumes:
      - ./flags.yaml:/goff/flags.yaml
      - ./goff-proxy.yaml:/goff/goff-proxy.yaml
    ports:
      - "1031:1031" # API + Swagger UI
    networks:
      - poc-net

networks:
  poc-net:
    external: true
    name: poc_feature_poc-net
