price-calculation:
  variations:
    enabled: true
    disabled: false
  defaultRule:
    variation: enabled
count-all-prices:
  variations:
    enabled: true
    disabled: false
  defaultRule:
    variation: enabled
view-all-prices:
  variations:
    enabled: true
    disabled: false
  defaultRule:
    variation: enabled
price-ingestion:
  variations:
    enabled: true
    disabled: false
  defaultRule:
    variation: enabled
materials-crud:
  variations:
    enabled: true
    disabled: false
  defaultRule:
    variation: enabled
costing-batch:
  variations:
    enabled: true
    disabled: false
  defaultRule:
    variation: enabled
population-jobs:
  variations:
    enabled: true
    disabled: false
  defaultRule:
    variation: enabled
view-all-components:
  variations:
    enabled: true
    disabled: false
  defaultRule:
    variation: enabled
