# GO Feature Flag Relay Proxy Configuration
# Docs: https://gofeatureflag.org/docs/relay_proxy/configure_relay_proxy

retriever:
  kind: file
  path: /goff/flags.yaml
  pollingInterval: 1000 # 1s polling

listen: 1031
enableSwagger: true
