receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

connectors:
  spanmetrics:
    metrics_flush_interval: 15s
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: http.route


    exemplars:
      enabled: true
    histogram:
      explicit:
        buckets: [2ms, 10ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s]
    namespace: traces.span.metrics
  
  servicegraph:
    latency_histogram_buckets: [2ms, 10ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s]
    dimensions:
      - http.method
      - http.status_code
      - span.kind

exporters:
  debug:
    verbosity: normal
  
  otlp/tempo:
    endpoint: tempo-1:4317
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"
    resource_to_telemetry_conversion:
      enabled: true
    # namespace removed to match standard dashboards

  loki:
    endpoint: http://loki-1:3100/loki/api/v1/push
    default_labels_enabled:
      exporter: true
      job: true

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, spanmetrics, servicegraph, debug]
    metrics:
      receivers: [otlp, spanmetrics, servicegraph]
      processors: [batch]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]
